# Generated by Django 2.0.2 on 2018-04-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_event_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostedPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
