# Generated by Django 2.0.2 on 2018-04-08 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_postedphoto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostedPhoto',
        ),
    ]
